In [1]:
import numpy as np
import random
from graphics import *
import math
import traceback
import sys

In [12]:
q_table = np.zeros((5, 5, 3))

"""
NOTHING = 0
HOUSE = 1
SOMEONE = 2
KIWI = 3
OUTSIDE = 4

left = 0
right = 1
forward = 2
"""

# If you see border, then you cannot go forward
for i in range(5):
    q_table[i][4][2] = -math.inf
print(q_table)

environment_table = np.zeros((10, 10), dtype = int)
environment_table[0][0] = 1 # House position
environment_table[9][9] = 3 # Kiwi position

start_pos = [5, 5]
start_pos_see = [6, 5]

def get_stand_state(stand_pos):
    if stand_pos[0] >= 10 or stand_pos[1] >= 10:
        return 4
    return environment_table[stand_pos[0]][stand_pos[1]]
def get_see_state(see_pos):
    if see_pos[0] >= 10 or see_pos[1] >= 10:
        return 4
    return environment_table[see_pos[0]][see_pos[1]]

    return environment_table[stand_pos[0]][stand_pos[1]] 
def get_state(stand_pos, see_pos):
    return get_stand_state(stand_pos), get_see_state(see_pos)

def get_possible_actions_from_state(state):
    possible_actions = []
    for i in range(3):
        if(q_table[state[0]][state[1]][i] != -math.inf):
            possible_actions.append(i)
    return possible_actions

print(get_state(start_pos, start_pos_see))
print(get_possible_actions_from_state(get_state(start_pos, start_pos_see)))


[[[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0. -inf]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0. -inf]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0. -inf]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0. -inf]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0. -inf]]]
(0, 0)
[0, 1, 2]


In [2]:
print(player.getCenter())
print(vision.getCenter())
playerPos = [math.floor(player.getCenter().getX()), math.floor(player.getCenter().getY())]
visionPos = [math.floor(vision.getCenter().getX()), math.floor(vision.getCenter().getY())]
left = [-1, 0]
print(playerPos, visionPos)

xDestination = playerPos[0] + left[0]
xPos = xDestination - visionPos[0]
yDestination = playerPos[1] + left[1]
yPos = yDestination - visionPos[1]
newPos = [xPos, yPos]
print(xDestination, yDestination, newPos)


NameError: name 'player' is not defined

In [3]:
class Movablevision():
    up = [0, 1]
    down = [0, -1]
    right = [1, 0] 
    left = [-1, 0]
    def __init__(self, window):
        self.win = window
        self.body = Rectangle(Point(5.3,5.3), Point(5.8,5.8)) # size 0.5
        self.body.draw(self.win)
        self.body.setFill("white")
        self.vision = Rectangle(Point(5,6), Point(6,7))
        self.vision.draw(self.win)
        self.vision.setFill("blue1")
        
        self.directions = [[1, 3], [2, 0], [3, 1], [0, 2]]
        self.moves = [[[-1, -1], [1, -1]], [[1, -1], [1, 1]], [[1, 1], [-1, 1]], [[-1, 1],[-1, -1]]]
        self.states = [self.up, self.left, self.down, self.right]
        self.currentState = 0
        
    def get_body_pos(self):
        return [math.floor(self.body.getCenter().getX()), math.floor(self.body.getCenter().getY())]
    
    def get_vision_pos(self):
        return [math.floor(self.vision.getCenter().getX()), math.floor(self.vision.getCenter().getY())]
    
    def move_forward(self):
        direction = self.states[self.currentState]
        self.vision.move(direction[0], direction[1])
        self.body.move(direction[0], direction[1])
    
    def restart(self):
        self.vision.undraw()
        self.vision = Rectangle(Point(5,6), Point(6,7))
        self.vision.draw(self.win)
        self.vision.setFill("blue1")
        self.body.undraw()
        self.body = Rectangle(Point(5.3,5.3), Point(5.8,5.8))
        self.body.draw(self.win)
        self.body.setFill("white")
        self.currentState = 0
    
    def look_left(self, left = True):
        nextState = self.directions[self.currentState][0 if left else 1]
        
        #print("\nCurrentState: ", self.currentState, "left: ", left)
        #print("nextState: ", nextState)
        
        playerPos = self.get_body_pos()
        visionPos = self.get_vision_pos()

        xPos = self.moves[self.currentState][0 if left else 1][0] #xDestination - visionPos[0]

        yPos = self.moves[self.currentState][0 if left else 1][1] #yDestination - visionPos[1]
        #print(xPos, yPos)
        #print("newPos", xPos, yPos)
        self.vision.move(xPos, yPos)
        self.currentState = nextState
        #print(self.vision.getP1(), self.vision.getP1())
        #print("newState: ", self.currentState)

In [4]:
class CoronaEnvironment():
    def __init__(self):
        try:
            self.win = GraphWin('Floor', 500, 500)
            self.win.setCoords(0.0, 0.0, 10.0, 10.0)
            self.win.setBackground("blue4")

            self.draw_grid()
            self.add_house()
            self.add_survivor()
            self.add_kiwi()
            
            self.main()   
            self.win.close()
        except Exception:
            print("Ooops, something is wrong")
            print(traceback.format_exc())
            if self.win != None:    
                self.win.close()
        
    def main(self):
        while True:
            k = self.win.checkKey()

            if k == 'Left':
                self.survivor.look_left()
            elif k == 'Right':
                self.survivor.look_left(False)
            elif k == 'Up':
                self.survivor.move_forward()
            elif k == 'Down':
                self.survivor.restart()
            elif k == 'period':
                break      
        
        
    def draw_grid(self):
        print("PlottingGrid")
        for x in range(10):
            for y in range(10):
                self.win.plotPixel(x*50, y*50, "yellow")
        print("FinishedPlotting")
    
    def add_house(self):
        print("add_house")
        
        self.housePos = [0, 0]
        house = Rectangle(Point(0,0), Point(1,1))
        house.draw(self.win)
        house.setFill("brown")
        print("add_house")
        
    
    def add_survivor(self):
        print("add_survivor")
        self.survivor = Movablevision(self.win)
        print("add_survivor")
        
        
    def add_kiwi(self):
        print("add_kiwi")
        
        self.kiwiPos = [9, 9]
        kiwi = Rectangle(Point(9,9), Point(10, 10))
        kiwi.draw(self.win)
        kiwi.setFill("green")
        print("add_kiwi")
    
    def reset_environment():
        self.survivor.reset()
    
    def get_state():
        vision_pos = self.survivor
    

In [5]:
CoronaEnvironment()

PlottingGrid
FinishedPlotting
add_house
add_house
add_survivor
add_survivor
add_kiwi
add_kiwi
Ooops, something is wrong
Traceback (most recent call last):
  File "<ipython-input-4-4b29e1717d5f>", line 13, in __init__
    self.main()
  File "<ipython-input-4-4b29e1717d5f>", line 23, in main
    k = self.win.checkKey()
  File "C:\Users\Maria\Anaconda3\lib\site-packages\graphics\__init__.py", line 352, in checkKey
    raise GraphicsError("checkKey in closed window")
graphics.GraphicsError: checkKey in closed window



In [6]:
win = GraphWin('Floor', 500, 500)

win.setCoords(0.0, 0.0, 10.0, 10.0)
win.setBackground("blue4")

# draw grid
for x in range(10):
    for y in range(10):
        win.plotPixel(x*50, y*50, "yellow")

house = Rectangle(Point(0,0), Point(1,1)) # size 0.5
house.draw(win)
house.setFill("brown")

player = Rectangle(Point(5.3,5.3), Point(5.8,5.8)) # size 0.5
player.draw(win)
player.setFill("white")
vision = Rectangle(Point(5,6), Point(6,7)) # size 0.5
vision.draw(win)
vision.setFill("blue1")
kiwi = Rectangle(Point(9,9), Point(10, 10)) # size 0.5
kiwi.draw(win)
kiwi.setFill("green")



win.getMouse()
win.close()

GraphicsError: getMouse in closed window

### Q Table
- See_states: null, someone, kiwi, house (4)
- Stand_states: null, someone, kiwi, house (4)
- Actions: left, right, forward (3)

### Rewards:
- Taking 1 action: -1 (faster is better)
- Standing on Kiwi: +10
- Standing with person: -5
- Getting home: +5 (terminates the game or after 100 actions)

In [ ]:
Q_table = np.zeros((4, 4, 3))
print(Q_table)

In [ ]:
total_episodes = 50        # Total episodes
total_test_episodes = 1     # Total test episodes
max_steps = 99                # Max steps per episode

learning_rate = 0.7           # Learning rate
gamma = 0.618                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob

In [ ]:
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0,1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        
        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()
        
        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * 
                                    np.max(qtable[new_state, :]) - qtable[state, action])
                
        # Our new state is state
        state = new_state
        
        # If done : finish episode
        if done == True: 
            break
    
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 